### ISSUE TITLE
Asset precompile is broken

### ISSUE THREAD

**Issue by Floppy** [theodi/open-data-certificate#1443]
```
ExecJS::ProgramError: Unexpected token: operator (>) (line: 6, col: 34, pos: 153)

Error
    at new JS_Parse_Error (<eval>:2357:10748)
    at js_error (<eval>:2357:10967)
    at croak (<eval>:2357:19192)
    at token_error (<eval>:2357:19329)
    at unexpected (<eval>:2357:19417)
    at expr_atom (<eval>:2357:27609)
    at maybe_unary (<eval>:2357:30102)
    at expr_ops (<eval>:2357:30860)
    at maybe_conditional (<eval>:2357:30952)
    at maybe_assign (<eval>:2357:31395)
  (in /usr/src/app/app/assets/javascripts/campaign_progress.js)/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:34:in `rescue in block in eval'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:28:in `block in eval'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:80:in `block in lock'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `call'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `Locker'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:27:in `eval'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:19:in `exec'
/usr/local/bundle/gems/uglifier-2.4.0/lib/uglifier.rb:184:in `really_compile'
/usr/local/bundle/gems/uglifier-2.4.0/lib/uglifier.rb:108:in `compile'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/compressors.rb:74:in `compress'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/processing.rb:265:in `block in js_compressor='
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/processor.rb:29:in `call'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/processor.rb:29:in `evaluate'
/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/context.rb:193:in `block in evaluate'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `each'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `evaluate'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/bundled_asset.rb:26:in `initialize'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `new'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `build_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:19:in `block in compile'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:219:in `block in each_logical_path'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each_entry'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:204:in `block in each_file'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each_file'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:217:in `each_logical_path'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:18:in `compile'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:56:in `internal_precompile'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
V8::Error: Unexpected token: operator (>)
at js_error (<eval>:2357:10967)
at croak (<eval>:2357:19192)
at token_error (<eval>:2357:19329)
at unexpected (<eval>:2357:19417)
at expr_atom (<eval>:2357:27609)
at maybe_unary (<eval>:2357:30102)
at expr_ops (<eval>:2357:30860)
at maybe_conditional (<eval>:2357:30952)
at maybe_assign (<eval>:2357:31395)
at maybe_assign (<eval>:2357:31569)
at expression (<eval>:2357:31708)
at vardefs (<eval>:2357:25924)
at var_ (<eval>:2357:26079)
at <eval>:2357:21868
at <eval>:2357:20063
at block_ (<eval>:2357:24682)
at ctor.body (<eval>:2357:24316)
at function_ (<eval>:2357:24381)
at expr_atom (<eval>:2357:27433)
at maybe_unary (<eval>:2357:30102)
at expr_ops (<eval>:2357:30860)
at maybe_conditional (<eval>:2357:30952)
at maybe_assign (<eval>:2357:31395)
at expression (<eval>:2357:31708)
at expr_list (<eval>:2357:27913)
at subscripts (<eval>:2357:29811)
at subscripts (<eval>:2357:29447)
at subscripts (<eval>:2357:29753)
at expr_atom (<eval>:2357:27570)
at maybe_unary (<eval>:2357:30102)
at expr_ops (<eval>:2357:30860)
at maybe_conditional (<eval>:2357:30952)
at maybe_assign (<eval>:2357:31395)
at expression (<eval>:2357:31708)
at simple_statement (<eval>:2357:22646)
at <eval>:2357:20659
at <eval>:2357:20063
at <eval>:2358:40
at parse (<eval>:2358:249)
at <eval>:19:26
at <eval>:53:3
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:29:in `block in eval'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:80:in `block in lock'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `call'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `Locker'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:27:in `eval'
/usr/local/bundle/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:19:in `exec'
/usr/local/bundle/gems/uglifier-2.4.0/lib/uglifier.rb:184:in `really_compile'
/usr/local/bundle/gems/uglifier-2.4.0/lib/uglifier.rb:108:in `compile'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/compressors.rb:74:in `compress'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/processing.rb:265:in `block in js_compressor='
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/processor.rb:29:in `call'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/processor.rb:29:in `evaluate'
/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/context.rb:193:in `block in evaluate'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `each'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `evaluate'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/bundled_asset.rb:26:in `initialize'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `new'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `build_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:19:in `block in compile'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:219:in `block in each_logical_path'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each_entry'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:204:in `block in each_file'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each_file'
/usr/local/bundle/gems/sprockets-2.2.3/lib/sprockets/base.rb:217:in `each_logical_path'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:18:in `compile'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:56:in `internal_precompile'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/usr/local/bin/ruby /usr/local/bundle/bin/...]
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/usr/local/bundle/gems/actionpack-3.2.21/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
```

**Comment by Floppy** [comment]
Is it the `=>` here? https://github.com/theodi/open-data-certificate/blob/staging/app/assets/javascripts/campaign_progress.js#L6
